
version: '2'

networks:
  netname:
    name: osqo-methodbridge

services:



  orderer0.osqo.osqo.com:
    extends:
      file: peer-base.yaml
      service: peer
    container_name: orderer0.osqo.osqo.com
    image: hyperledger/fabric-orderer:2.4.4
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=osqoMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ../system-genesis-file/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/peerOrganizations/osqo.osqo.com/peers/orderer0.osqo.osqo.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/peerOrganizations/osqo.osqo.com/peers/orderer0.osqo.osqo.com/tls/:/var/hyperledger/orderer/tls
        - ../../network-data/orderer0.osqo.osqo.com:/var/hyperledger/production/orderer
    networks:
      - netname


  peer0.osqo.osqo.com:
    extends:
      file: peer-base.yaml
      service: peer
    container_name: peer0.osqo.osqo.com
    image: hyperledger/fabric-peer:2.4.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=osqo-methodbridge
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.osqo.osqo.com
      - CORE_PEER_ADDRESS=peer0.osqo.osqo.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.osqo.osqo.com:11052
      # - CORE_PEER_CHAINCODEADDRESS=peer0.osqo.osqo.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.osqo.osqo.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.osqo.osqo.com:11051
      - CORE_PEER_LOCALMSPID=osqoMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-osqo-peer0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=osqo1Admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=osqo1Adminpw
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/osqo.osqo.com/peers/peer0.osqo.osqo.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/osqo.osqo.com/peers/peer0.osqo.osqo.com/tls:/etc/hyperledger/fabric/tls
        - ../../network-data/peer0.osqo.osqo.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11051:11051
    networks:
      - netname
    depends_on:
      - couchdb-osqo-peer0         

  peer1.osqo.osqo.com:
    extends:
      file: peer-base.yaml
      service: peer
    container_name: peer1.osqo.osqo.com
    image: hyperledger/fabric-peer:2.4.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=osqo-methodbridge
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.osqo.osqo.com
      - CORE_PEER_ADDRESS=peer1.osqo.osqo.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.osqo.osqo.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.osqo.osqo.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.osqo.osqo.com:12051
      - CORE_PEER_LOCALMSPID=osqoMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-osqo-peer1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=osqo2Admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=osqo2Adminpw
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/osqo.osqo.com/peers/peer1.osqo.osqo.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/osqo.osqo.com/peers/peer1.osqo.osqo.com/tls:/etc/hyperledger/fabric/tls
        - ../../network-data/peer1.osqo.osqo.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 12051:12051
    networks:
      - netname 
    depends_on:
      - couchdb-osqo-peer1    

  couchdb-osqo-peer0:
    container_name: couchdb-osqo-peer0
    image: couchdb:3.1.1

    environment:
      - COUCHDB_USER=osqo1Admin
      - COUCHDB_PASSWORD=osqo1Adminpw
    ports:
      - 5984:5984
    networks:
      - netname

  couchdb-osqo-peer1:
    container_name: couchdb-osqo-peer1
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=osqo2Admin
      - COUCHDB_PASSWORD=osqo2Adminpw
    ports:
      - 6984:5984
    networks:
      - netname   

