version: "2"

services:
  peer:
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=osqo-methodbridge
      - CORE_LOGGING_LEVEL=INFO
      - FABRIC_LOGGING_SPEC=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
    # working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # command: peer node start
    extra_hosts:
      - peer10.osqo.osqo.com:127.0.0.1
      # - peer1.osqo.osqo.com:127.0.0.1
      # - orderer0.osqo.osqo.com:127.0.0.1
      # - peer0.bcp.osqo.com:127.0.0.1
      # - peer1.bcp.osqo.com:127.0.0.1
      # - orderer0.bcp.osqo.com:127.0.0.1
      # - peer0.esp.osqo.com:127.0.0.1
      # - peer1.esp.osqo.com:127.0.0.1
      # - orderer0.esp.osqo.com:127.0.0.1
      # - peer0.broker.osqo.com:127.0.0.1
      # - peer1.broker.osqo.com:127.0.0.1
      # - orderer0.broker.osqo.com:127.0.0.1
