
Organizations:

    - &Osqo
       
        Name: osqoMSP
        

        # ID to load the MSP definition as
        ID: osqoMSP

        MSPDir: ../organizations/peerOrganizations/osqo.osqo.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: OR('osqoMSP.admin', 'osqoMSP.peer', 'osqoMSP.client')
            Writers:
                Type: Signature
                Rule: OR('osqoMSP.admin', 'osqoMSP.client', 'osqoMSP.orderer')
            Admins:
                Type: Signature
                Rule: OR('osqoMSP.admin')
            Endorsement:
                Type: Signature
                Rule: OR('osqoMSP.peer')

        OrdererEndpoints:
            - orderer0.osqo.osqo.com:7050

        AnchorPeers:
            - Host: peer0.osqo.osqo.com
              Port: 11051        

    - &Bcp
    
        Name: bcpMSP

        # ID to load the MSP definition as
        ID: bcpMSP

        MSPDir: ../organizations/peerOrganizations/bcp.osqo.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: OR('bcpMSP.admin', 'bcpMSP.peer', 'bcpMSP.client')
            Writers:
                Type: Signature
                Rule: OR('bcpMSP.admin', 'bcpMSP.client', 'bcpMSP.orderer')
            Admins:
                Type: Signature
                Rule: OR('bcpMSP.admin')
            Endorsement:
                Type: Signature
                Rule: OR('bcpMSP.peer')

        OrdererEndpoints:
            - orderer0.bcp.osqo.com:12050

        AnchorPeers:       
            - Host: peer0.bcp.osqo.com
              Port: 13051 
              
    - &Esp
        
        Name: espMSP

        # ID to load the MSP definition as
        ID: espMSP

        MSPDir: ../organizations/peerOrganizations/esp.osqo.com/msp

       
        Policies:
            Readers:
                Type: Signature
                Rule: OR('espMSP.admin', 'espMSP.peer', 'espMSP.client')
            Writers:
                Type: Signature
                Rule: OR('espMSP.admin', 'espMSP.client', 'espMSP.orderer')
            Admins:
                Type: Signature
                Rule: OR('espMSP.admin')
            Endorsement:
                Type: Signature
                Rule: OR('espMSP.peer')

        OrdererEndpoints:
            - orderer0.esp.osqo.com:13050

        AnchorPeers:
            - Host: peer0.esp.osqo.com
              Port: 15051  

    - &Broker
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: brokerMSP

        # ID to load the MSP definition as
        ID: brokerMSP

        MSPDir: ../organizations/peerOrganizations/broker.osqo.com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: OR('brokerMSP.admin', 'brokerMSP.peer', 'brokerMSP.client')
            Writers:
                Type: Signature
                Rule: OR('brokerMSP.admin', 'brokerMSP.client', 'brokerMSP.orderer')
            Admins:
                Type: Signature
                Rule: OR('brokerMSP.admin')
            Endorsement:
                Type: Signature
                Rule: OR('brokerMSP.peer')
        
        OrdererEndpoints:
            - orderer0.broker.osqo.com:14050

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.broker.osqo.com
              Port: 17051                    

################################################################################
#
#   SECTION: Capabilities

################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#
#   SECTION: Application
#
################################################################################
Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: MAJORITY Endorsement
        Endorsement:
            Type: ImplicitMeta
            Rule: MAJORITY Endorsement

    Capabilities:
        <<: *ApplicationCapabilities
################################################################################
#
#   SECTION: Orderer
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    OrdererType: etcdraft
    
    Addresses:
        - orderer0.osqo.osqo.com:7050
        - orderer0.bcp.osqo.com:12050
        - orderer0.esp.osqo.com:13050
        - orderer0.broker.osqo.com:14050
        

    EtcdRaft:
        Consenters:
        - Host: orderer0.osqo.osqo.com
          Port: 7050 
          ClientTLSCert: ../organizations/peerOrganizations/osqo.osqo.com/peers/orderer0.osqo.osqo.com/tls/server.crt
          ServerTLSCert: ../organizations/peerOrganizations/osqo.osqo.com/peers/orderer0.osqo.osqo.com/tls/server.crt
        - Host: orderer0.bcp.osqo.com
          Port: 12050 
          ClientTLSCert: ../organizations/peerOrganizations/bcp.osqo.com/peers/orderer0.bcp.osqo.com/tls/server.crt
          ServerTLSCert: ../organizations/peerOrganizations/bcp.osqo.com/peers/orderer0.bcp.osqo.com/tls/server.crt
        - Host: orderer0.esp.osqo.com
          Port: 13050 
          ClientTLSCert: ../organizations/peerOrganizations/esp.osqo.com/peers/orderer0.esp.osqo.com/tls/server.crt
          ServerTLSCert: ../organizations/peerOrganizations/esp.osqo.com/peers/orderer0.esp.osqo.com/tls/server.crt
        - Host: orderer0.broker.osqo.com
          Port: 14050 
          ClientTLSCert: ../organizations/peerOrganizations/broker.osqo.com/peers/orderer0.broker.osqo.com/tls/server.crt
          ServerTLSCert: ../organizations/peerOrganizations/broker.osqo.com/peers/orderer0.broker.osqo.com/tls/server.crt
        



    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: ANY Writers
    Capabilities:
        <<: *OrdererCapabilities        

################################################################################
#
#   CHANNEL
#
################################################################################
Channel: &ChannelDefaults
    Policies:
        # Who may invoke the 'Deliver' API
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins

    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
################################################################################
Profiles:

    OrgsOrdererGenesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Osqo
                - *Bcp
                - *Esp
                - *Broker
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            OsqoConsortium:
                Organizations:
                    - *Osqo
                    - *Bcp
                    - *Esp
                    - *Broker
    OrgsChannel:
        Consortium: OsqoConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Osqo
                - *Bcp
                - *Esp
                - *Broker
            Capabilities:
                <<: *ApplicationCapabilities

    MultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer0.osqo.osqo.com
                  Port: 7050
                  ClientTLSCert: ../organizations/peerOrganizations/osqo.osqo.com/peers/orderer0.osqo.osqo.com/tls/server.crt
                  ServerTLSCert: ../organizations/peerOrganizations/osqo.osqo.com/peers/orderer.osqo.osqo.com/tls/server.crt
                - Host: orderer0.bcp.osqo.com
                  Port: 7050
                  ClientTLSCert: ../organizations/peerOrganizations/bcp.osqo.com/peers/orderer0.bcp.osqo.com/tls/server.crt
                  ServerTLSCert: ../organizations/peerOrganizations/bcp.osqo.com/peers/orderer0.bcp.osqo.com/tls/server.crt
                - Host: orderer0.broker.osqo.com
                  Port: 7050
                  ClientTLSCert: ../organizations/peerOrganizations/broker.osqo.com/peers/orderer0.broker.osqo.com/tls/server.crt
                  ServerTLSCert: ../organizations/peerOrganizations/broker.osqo.com/peers/orderer0.broker.osqo.com/tls/server.crt
                - Host: orderer0.esp.osqo.com
                  Port: 7050
                  ClientTLSCert: ../organizations/peerOrganizations/esp.osqo.com/peers/orderer0.esp.osqo.com/tls/server.crt
                  ServerTLSCert: ../organizations/peerOrganizations/esp.osqo.com/peers/orderer0.esp.osqo.com/tls/server.crt

            Addresses:
                - orderer0.osqo.osqo.com:7050
                - orderer0.bcp.osqo.com:8050
                - orderer0.esp.osqo.com:9050
                - orderer0.broker.osqo.com:10050
                

            # Organizations:
            # - *Orderermethodbridge
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            # Organizations:
            # - <<: *Orderermethodbridge
        Consortiums:
            OsqoConsortium:
                Organizations:
                - *Osqo
                - *Bcp
                - *Esp
                - *Broker

